### ISSUE TITLE
MyBinder OptimizationDataset example is broken

### ISSUE THREAD

**Issue by jchodera** [MolSSI/QCArchiveExamples#15]
@bennybp @dotsdl : The `OptimizationDataset` example on MyBinder launched from [here](https://qcarchive.molssi.org/examples/) appears to be broken:

![image](https://user-images.githubusercontent.com/3656088/96046630-a5519500-0e28-11eb-8ee8-803a6907579a.png)

**Comment by bennybp** [comment]
Looks like the client is out of date, despite what the error message says.

The error string is incorrect because the client version is actually the minimum server version

https://github.com/MolSSI/QCFractal/blob/268db782a0c37bbe3e5bd335803232ea48a7bfd4/qcfractal/interface/client.py#L162

**Comment by jchodera** [comment]
What would be required to update the examples?

**Comment by bennybp** [comment]
Looks like there needed to be a commit to this repo to trigger building a new docker container for mybinder. It is working for me now.

**Comment by jchodera** [comment]
That's odd. [The Binder link](https://mybinder.org/v2/gh/MolSSI/QCArchiveExamples/master?urlpath=lab/tree/basic_examples) isn't launching the notebook for me now:
![image](https://user-images.githubusercontent.com/3656088/96062713-39ccef00-0e4b-11eb-9e2e-4551302958da.png)

**Comment by bennybp** [comment]
I think it is working for me (after selecting the notebook)

![image](https://user-images.githubusercontent.com/4708439/96138313-a25bb080-0ecb-11eb-96ba-6cec1a7e47c1.png)

**Comment by dotsdl** [comment]
Just gave this a shot myself; the [binder link](https://mybinder.org/v2/gh/MolSSI/QCArchiveExamples//master?urlpath=lab/tree/basic_examples/optimization_datasets.ipynb) drops me straight into the correct notebook, and notebook executes without error (though NGLView doesn't render). Does this work for you in the same way now @jchodera?

**Comment by jchodera** [comment]
Works for me now, thanks!
